spring.application.name=event-service

user.service.url=http://localhost:8081

server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/Connexus
spring.datasource.username=postgres
spring.datasource.password=Nani@9769

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=a29659a70f0ef135a1ca2b828f2acc5956d3c2b0